# Example config file
# Contains maximal configuration for each generator.
# All parameters have defaults and are optional.
---
name: app # Determines the endpoint (e.g. /app)
secrets:
  # AlphaNumeric Generator
  - name: api_key
    type: AlphaNumeric
    parameters:
      length: 32 # Length of the generated string

  # BasicAuth Generator
  - name: login
    type: BasicAuth
    parameters:
      username: steve # The username
      length: 32 # Length of the generated password

  # BCrypt Generator
  - name: password
    type: BCrypt
    parameters:
      length: 16 # Length of the string used for the hash

  # PBKD2 Generator
  - name: client_secret
    type: PBKDF2
    parameters:
      digest_name: client_secret_digest # Name of the key containing the digest
      length: 32 # Length of the string used for the hash
      iterations: 310000 # Number of rounds
      salt_length: 16 # Length of the string used for the salt

  # UUID Generator
  - name: uuid
    type: UUID
    # No parameters needed
