---
apiVersion: generators.external-secrets.io/v1alpha1
kind: Webhook
metadata:
  name: sabnzbd
spec:
  method: POST
  url: "http://secret-generator.test.svc.cluster.local:80/sabnzbd"
  result:
    jsonPath: "$"
  headers:
    Content-Type: application/json
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: sabnzbd
spec:
  refreshInterval: 0m # do not refresh
  target:
    name: sabnzbd
  dataFrom:
    - sourceRef:
        generatorRef:
          apiVersion: generators.external-secrets.io/v1alpha1
          kind: Webhook
          name: sabnzbd