---
name: Build Container

on:
    push:
      branches:
          - main
    pull_request:

jobs:
    build-image:
        name: Build Images
        runs-on: ubuntu-latest
        steps:
            - name: Set up QEMU
              uses: docker/setup-qemu-action@v3

            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v3

            - name: Login to GitHub Container Registry
              uses: docker/login-action@v3
              with:
                registry: ghcr.io
                username: ${{ github.repository_owner }}
                password: ${{ secrets.GITHUB_TOKEN }}

            - name: Docker build and push
              uses: docker/build-push-action@v6
              env:
                BUILDX_NO_DEFAULT_ATTESTATIONS: 1
              with:
                push: ${{ github.event_name != 'pull_request' }}
                tags: ghcr.io/stevewm/secretgenerator:0.0.1
                cache-from: type=gha
                cache-to: type=gha,mode=max
                platforms: linux/amd64,linux/arm64
